mae_cfg = [ dict(type='MAE',
                    img_size=11,
                    patch_size=1, 
                    student_encoder_in_chans=256,
                    teacher_encoder_in_chans=256,        
                    # encoder settings 
                    encoder_embed_dim=256, #512
                    encoder_depth=4, 
                    encoder_num_heads=8,
                    encoder_num_classes=0,
                    # decoder settings
                    decoder_embed_dim=256,
                    decoder_num_classes=256,
                    decoder_depth=4,
                    decoder_num_heads=8,
                    mlp_ratio=4, 
                    qkv_bias=True,        
                ),
            dict(type='MAE', 
                    img_size=21,
                    patch_size=1, 
                    student_encoder_in_chans=256,
                    teacher_encoder_in_chans=256,        
                    # encoder settings 
                    encoder_embed_dim=256, #512
                    encoder_depth=4, 
                    encoder_num_heads=8,
                    encoder_num_classes=0,
                    # decoder settings
                    decoder_embed_dim=256,
                    decoder_num_classes=256,
                    decoder_depth=4,
                    decoder_num_heads=8,
                    mlp_ratio=4, 
                    qkv_bias=True,        
                ),
               dict(type='MAE',
                    img_size=42,
                    patch_size=2, 
                    student_encoder_in_chans=256,
                    teacher_encoder_in_chans=256,        
                    # encoder settings 
                    encoder_embed_dim=256,
                    encoder_depth=4, 
                    encoder_num_heads=8,
                    encoder_num_classes=0,
                    # decoder settings
                    decoder_embed_dim=512,
                    decoder_num_classes=256*2*2,
                    decoder_depth=4,
                    decoder_num_heads=8,
                    mlp_ratio=4, 
                    qkv_bias=True,        
                ),
                dict(type='MAE',
                    img_size=84,
                    patch_size=4, 
                    student_encoder_in_chans=256,
                    teacher_encoder_in_chans=256,        
                    # encoder settings 
                    encoder_embed_dim=512,
                    encoder_depth=4, 
                    encoder_num_heads=8,
                    encoder_num_classes=0,
                    # decoder settings
                    decoder_embed_dim=1024,
                    decoder_num_classes=256*4*4,
                    decoder_depth=4,
                    decoder_num_heads=8,
                    mlp_ratio=4, 
                    qkv_bias=True,        
                ),
                # dict(type='MAE',
                #     img_size=167,
                #     patch_size=1, 
                #     student_encoder_in_chans=256,
                #     teacher_encoder_in_chans=256,        
                #     # encoder settings 
                #     encoder_embed_dim=256, #512
                #     encoder_depth=2, 
                #     encoder_num_heads=8,
                #     encoder_num_classes=0,
                #     # decoder settings
                #     decoder_embed_dim=256,
                #     decoder_num_classes=256,
                #     decoder_depth=2,
                #     decoder_num_heads=8,
                #     mlp_ratio=4, 
                #     qkv_bias=True,        
                # ),
    ]